<?php

use Illuminate\Database\Seeder;

class DocumentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $documents = [
    		[
                'catelog'   =>  'WEB APPLICATION',
                'title'     =>  'Web Programing',
                'content'   =>  'They stepped inside the cave. Pitch-black it was. The old man shook open his fist and a ball of light suddenly appeared, brightening the cave.  Under the light with one long finger, he drew the shape of a circle over the ground. He pulled from his pocket some red dust and threw it over the circle, and at the same time said some magic words. The earth trembled a little before them. The floor of the cave cracked open, and the cracks grew wider and deeper. Then up from below the ground rose a giant white quartz crystal and it filled the circle. “Fear nothing,” said the magician to Aladdin. “But obey me. Go down, and at the foot of the steps, follow a long hall.  You will walk through a garden of fruit trees. You must touch nothing of them. Walk on till you come to a large flat stone and on the stone will be a lighted lamp. Pour out the oil in the lamp and bring it to me. Now go!” Aladdin slowly stepped down the stairs.  Through the garden of fruit trees and marvelous to behold, the trees held fruits that sparkled and shone. He could not help but reach out and touch one. Then – too late – he remembered what his uncle had said. But nothing terrible happened. So he figured he might as well put the fine jewel-fruit in his vest pocket. Then he plucked another and another jewel-fruit, till all his pockets were filled. Aladdin came to the large flat stone, and on it was a lighted lamp, just as his uncle had said.He poured out the oil and took it back to the opening of the cave.',
                'image'     =>  'web-outsourcing.jpg',
            ],
            [
                'catelog'   =>  'WEB APPLICATION',
                'title'     =>  'Shopping website',
                'content'   =>  'They stepped inside the cave. Pitch-black it was. The old man shook open his fist and a ball of light suddenly appeared, brightening the cave.  Under the light with one long finger, he drew the shape of a circle over the ground. He pulled from his pocket some red dust and threw it over the circle, and at the same time said some magic words. The earth trembled a little before them. The floor of the cave cracked open, and the cracks grew wider and deeper. Then up from below the ground rose a giant white quartz crystal and it filled the circle. “Fear nothing,” said the magician to Aladdin. “But obey me. Go down, and at the foot of the steps, follow a long hall.  You will walk through a garden of fruit trees. You must touch nothing of them. Walk on till you come to a large flat stone and on the stone will be a lighted lamp. Pour out the oil in the lamp and bring it to me. Now go!” Aladdin slowly stepped down the stairs.  Through the garden of fruit trees and marvelous to behold, the trees held fruits that sparkled and shone. He could not help but reach out and touch one. Then – too late – he remembered what his uncle had said. But nothing terrible happened. So he figured he might as well put the fine jewel-fruit in his vest pocket. Then he plucked another and another jewel-fruit, till all his pockets were filled. Aladdin came to the large flat stone, and on it was a lighted lamp, just as his uncle had said.He poured out the oil and took it back to the opening of the cave.',
                'image'     =>  'shopping-website.jpg',
            ],
            [
                'catelog'   =>  'WEB APPLICATION',
                'title'     =>  'Portal',
                'content'   =>  'They stepped inside the cave. Pitch-black it was. The old man shook open his fist and a ball of light suddenly appeared, brightening the cave.  Under the light with one long finger, he drew the shape of a circle over the ground. He pulled from his pocket some red dust and threw it over the circle, and at the same time said some magic words. The earth trembled a little before them. The floor of the cave cracked open, and the cracks grew wider and deeper. Then up from below the ground rose a giant white quartz crystal and it filled the circle. “Fear nothing,” said the magician to Aladdin. “But obey me. Go down, and at the foot of the steps, follow a long hall.  You will walk through a garden of fruit trees. You must touch nothing of them. Walk on till you come to a large flat stone and on the stone will be a lighted lamp. Pour out the oil in the lamp and bring it to me. Now go!” Aladdin slowly stepped down the stairs.  Through the garden of fruit trees and marvelous to behold, the trees held fruits that sparkled and shone. He could not help but reach out and touch one. Then – too late – he remembered what his uncle had said. But nothing terrible happened. So he figured he might as well put the fine jewel-fruit in his vest pocket. Then he plucked another and another jewel-fruit, till all his pockets were filled. Aladdin came to the large flat stone, and on it was a lighted lamp, just as his uncle had said.He poured out the oil and took it back to the opening of the cave.',
                'image'     =>  'cms-site.jpg',
            ],
            [
                'catelog'   =>  'WEB APPLICATION',
                'title'     =>  'Real estate',
                'content'   =>  'They stepped inside the cave. Pitch-black it was. The old man shook open his fist and a ball of light suddenly appeared, brightening the cave.  Under the light with one long finger, he drew the shape of a circle over the ground. He pulled from his pocket some red dust and threw it over the circle, and at the same time said some magic words. The earth trembled a little before them. The floor of the cave cracked open, and the cracks grew wider and deeper. Then up from below the ground rose a giant white quartz crystal and it filled the circle. “Fear nothing,” said the magician to Aladdin. “But obey me. Go down, and at the foot of the steps, follow a long hall.  You will walk through a garden of fruit trees. You must touch nothing of them. Walk on till you come to a large flat stone and on the stone will be a lighted lamp. Pour out the oil in the lamp and bring it to me. Now go!” Aladdin slowly stepped down the stairs.  Through the garden of fruit trees and marvelous to behold, the trees held fruits that sparkled and shone. He could not help but reach out and touch one. Then – too late – he remembered what his uncle had said. But nothing terrible happened. So he figured he might as well put the fine jewel-fruit in his vest pocket. Then he plucked another and another jewel-fruit, till all his pockets were filled. Aladdin came to the large flat stone, and on it was a lighted lamp, just as his uncle had said.He poured out the oil and took it back to the opening of the cave.',
                'image'     =>  'bds-site.jpg',
            ],
            [
                'catelog'   =>  'MOBILE GAME',
                'title'     =>  'Game with cocos2d',
                'content'   =>  'They stepped inside the cave. Pitch-black it was. The old man shook open his fist and a ball of light suddenly appeared, brightening the cave.  Under the light with one long finger, he drew the shape of a circle over the ground. He pulled from his pocket some red dust and threw it over the circle, and at the same time said some magic words. The earth trembled a little before them. The floor of the cave cracked open, and the cracks grew wider and deeper. Then up from below the ground rose a giant white quartz crystal and it filled the circle. “Fear nothing,” said the magician to Aladdin. “But obey me. Go down, and at the foot of the steps, follow a long hall.  You will walk through a garden of fruit trees. You must touch nothing of them. Walk on till you come to a large flat stone and on the stone will be a lighted lamp. Pour out the oil in the lamp and bring it to me. Now go!” Aladdin slowly stepped down the stairs.  Through the garden of fruit trees and marvelous to behold, the trees held fruits that sparkled and shone. He could not help but reach out and touch one. Then – too late – he remembered what his uncle had said. But nothing terrible happened. So he figured he might as well put the fine jewel-fruit in his vest pocket. Then he plucked another and another jewel-fruit, till all his pockets were filled. Aladdin came to the large flat stone, and on it was a lighted lamp, just as his uncle had said.He poured out the oil and took it back to the opening of the cave.',
                'image'     =>  'game-cocos.jpg',
            ],
            [
                'catelog'   =>  'MOBILE GAME',
                'title'     =>  'Real estate',
                'content'   =>  'They stepped inside the cave. Pitch-black it was. The old man shook open his fist and a ball of light suddenly appeared, brightening the cave.  Under the light with one long finger, he drew the shape of a circle over the ground. He pulled from his pocket some red dust and threw it over the circle, and at the same time said some magic words. The earth trembled a little before them. The floor of the cave cracked open, and the cracks grew wider and deeper. Then up from below the ground rose a giant white quartz crystal and it filled the circle. “Fear nothing,” said the magician to Aladdin. “But obey me. Go down, and at the foot of the steps, follow a long hall.  You will walk through a garden of fruit trees. You must touch nothing of them. Walk on till you come to a large flat stone and on the stone will be a lighted lamp. Pour out the oil in the lamp and bring it to me. Now go!” Aladdin slowly stepped down the stairs.  Through the garden of fruit trees and marvelous to behold, the trees held fruits that sparkled and shone. He could not help but reach out and touch one. Then – too late – he remembered what his uncle had said. But nothing terrible happened. So he figured he might as well put the fine jewel-fruit in his vest pocket. Then he plucked another and another jewel-fruit, till all his pockets were filled. Aladdin came to the large flat stone, and on it was a lighted lamp, just as his uncle had said.He poured out the oil and took it back to the opening of the cave.',
                'image'     =>  'game-unity.png',
            ],
            [
                'catelog'   =>  'MOBILE GAME',
                'title'     =>  'Integration with 3rd',
                'content'   =>  'They stepped inside the cave. Pitch-black it was. The old man shook open his fist and a ball of light suddenly appeared, brightening the cave.  Under the light with one long finger, he drew the shape of a circle over the ground. He pulled from his pocket some red dust and threw it over the circle, and at the same time said some magic words. The earth trembled a little before them. The floor of the cave cracked open, and the cracks grew wider and deeper. Then up from below the ground rose a giant white quartz crystal and it filled the circle. “Fear nothing,” said the magician to Aladdin. “But obey me. Go down, and at the foot of the steps, follow a long hall.  You will walk through a garden of fruit trees. You must touch nothing of them. Walk on till you come to a large flat stone and on the stone will be a lighted lamp. Pour out the oil in the lamp and bring it to me. Now go!” Aladdin slowly stepped down the stairs.  Through the garden of fruit trees and marvelous to behold, the trees held fruits that sparkled and shone. He could not help but reach out and touch one. Then – too late – he remembered what his uncle had said. But nothing terrible happened. So he figured he might as well put the fine jewel-fruit in his vest pocket. Then he plucked another and another jewel-fruit, till all his pockets were filled. Aladdin came to the large flat stone, and on it was a lighted lamp, just as his uncle had said.He poured out the oil and took it back to the opening of the cave.',
                'image'     =>  'game-admod.png',
            ],
            [
                'catelog'   =>  'MOBILE APPLICATION',
                'title'     =>  'Cross Platform Application',
                'content'   =>  'They stepped inside the cave. Pitch-black it was. The old man shook open his fist and a ball of light suddenly appeared, brightening the cave.  Under the light with one long finger, he drew the shape of a circle over the ground. He pulled from his pocket some red dust and threw it over the circle, and at the same time said some magic words. The earth trembled a little before them. The floor of the cave cracked open, and the cracks grew wider and deeper. Then up from below the ground rose a giant white quartz crystal and it filled the circle. “Fear nothing,” said the magician to Aladdin. “But obey me. Go down, and at the foot of the steps, follow a long hall.  You will walk through a garden of fruit trees. You must touch nothing of them. Walk on till you come to a large flat stone and on the stone will be a lighted lamp. Pour out the oil in the lamp and bring it to me. Now go!” Aladdin slowly stepped down the stairs.  Through the garden of fruit trees and marvelous to behold, the trees held fruits that sparkled and shone. He could not help but reach out and touch one. Then – too late – he remembered what his uncle had said. But nothing terrible happened. So he figured he might as well put the fine jewel-fruit in his vest pocket. Then he plucked another and another jewel-fruit, till all his pockets were filled. Aladdin came to the large flat stone, and on it was a lighted lamp, just as his uncle had said.He poured out the oil and took it back to the opening of the cave.',
                'image'     =>  'cross-platform.jpg',
            ]
        ];
        DB::table('documents')->insert($documents);
    }
}
