export const dateOffConstants = {
  CREATE_DATE_OFF: "CREATE_DATE_OFF",

  GET_DATEOFF_REQUEST:"GET_DATEOFF_REQUEST",
  GET_DATEOFF_SUCCESS:"GET_DATEOFF_SUCCESS",

  DELETE_DATEOFF:"DELETE_DATEOFF",

  GET_DATEOFF_ACCEPT_SUCCESS:"GET_DATEOFF_ACCEPT_SUCCESS"
};
