export const overtimeConstants = {
  CREATE_NEW_TEAM: "CREATE_NEW_TEAM",

  GETALL_TEAM_REQUEST: "OVERTIME_GETALL_REQUEST",
  GETALL_TEAM_SUCCESS: "OVERTIME_GETALL_SUCCESS",
  GETALL_TEAM_FAILURE: "OVERTIME_GETALL_FAILURE",

  GETONE_TEAM_REQUEST: "OVERTIME_GETONE_REQUEST",
  GETONE_TEAM_SUCCESS: "OVERTIME_GETONE_SUCCESS",
  GETONE_TEAM_FAILURE: "OVERTIME_GETONE_FAILURE",

  MEMBER_REQUEST: "OVERTIME_MEMBER_REQUEST",
  MEMBER_SUCCESS: "OVERTIME_MEMBER_SUCCESS",
  MEMBER_FAILURE: "OVERTIME_MEMBER_FAILURE",

  ADD_MEMBER: "ADD_MEMBER",
  ADD_TEAM: "ADD_TEAM ",

  DELETE_MEMBER_ITEM: "DELETE_MEMBER_ITEM",
  DELETE_MEMBER_SUCCESS: "DELETE_MEMBER_SUCCESS",
  ADD_TEAM: "ADD_TEAM ",
  DELETE_TEAM: "DELETE_TEAM",

  ADD_OVERTIME: "ADD_OVERTIME",

  GET_MEMBER_IN_TEAM_REQUEST: "GET_MEMBER_IN_TEAM_REQUEST",
  GET_MEMBER_IN_TEAM_SUCCESS: "GET_MEMBER_IN_TEAM_SUCCESS",
  GET_MEMBER_IN_TEAM_FAILURE: "GET_MEMBER_IN_TEAM_FAILURE",

  GET_ALL_MEMBER_IN_TEAM_OT_REQUEST: "GET_ALL_MEMBER_IN_TEAM_OT_REQUEST",
  GET_ALL_MEMBER_IN_TEAM_OT_SUCCESS: "GET_ALL_MEMBER_IN_TEAM_OT_SUCCESS",
  UPDATE_OVERTIME_SUCCESS: "UPDATE_OVERTIME_SUCCESS",

  GETALL_OT_REQUEST: "GETALL_OT_REQUEST",
  GETALL_OT_SUCCESS: "GETALL_OT_SUCCESS",

  GET_OT_ONE_USER_SUCCESS: "GET_OT_ONE_USER_SUCCESS",

  GET_ONE_MEMBER_OT_IN_TEAM_SUCCESS: "GET_ONE_MEMBER_OT_IN_TEAM_SUCCESS"
};
