export const userConstants = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",
  CREATE_NEW_USER: "CREATE_NEW_USER",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",

  DELETE_ITEM: "DELETE_ITEM",

  GETONE_REQUEST: "USERS_GETONE_REQUEST",
  GETONE_SUCCESS: "USERS_GETONE_SUCCESS",
  GETME_SUCCESS: "USERS_GETME_SUCCESS",
  GETONE_FAILURE: "USERS_GETONE_FAILURE",

  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  TOKEN_FAILURE: "TOKEN_FAILURE",
  TOKEN_SUCCESS: "TOKEN_SUCCESS",

  SENDEMAIL_REQUEST: "SENDEMAIL_REQUEST",
  SENDEMAIL_SUCCESS: "SENDEMAIL_SUCCESS"
};

export const img_path = "/storage/uploads/";
